import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

/**
 * Resume file storage seam.
 *
 * Per the data-model spec (issue #2), resume files themselves never touch
 * Postgres -- only an (encrypted) *reference* to where the file lives does
 * (`profiles.resume_file_url_encrypted`). This interface is that storage
 * backend, kept pluggable the same way `KeyProvider` (encryption.ts) is:
 * swap in a real implementation later without touching any call site.
 *
 * Production is expected to implement this against S3-compatible object
 * storage (encrypted at rest via the bucket, per issue #2) -- which provider
 * is an open infra decision tied to a hosting choice that hasn't been made
 * yet (same open question `packages/db/README.md` already flags for
 * `KeyProvider`). `LocalDiskResumeStorage` below is the dev/test default and
 * is NOT sufficient for production: no encryption at rest, no redundancy,
 * and it only works when the app runs on a single machine with a persistent
 * disk.
 */
export interface ResumeStorage {
  put(objectKey: string, file: { buffer: Buffer }): Promise<void>;
  get(objectKey: string): Promise<Buffer | null>;
  delete(objectKey: string): Promise<void>;
}

/**
 * Dev/test resume storage: writes to a local directory (default
 * `RESUME_STORAGE_DIR`, falling back to `.data/resumes` under this
 * package). NOT for production -- see the `ResumeStorage` doc comment.
 */
export class LocalDiskResumeStorage implements ResumeStorage {
  private readonly rootDir: string;

  constructor(rootDir = process.env.RESUME_STORAGE_DIR || join(__dirname, "..", ".data", "resumes")) {
    this.rootDir = rootDir;
  }

  private pathFor(objectKey: string): string {
    // objectKey is always generated by our own code (see postgres.ts --
    // `resumes/${userId}/${resumeId}`), never taken from user input, so a
    // plain join is safe here (no path-traversal surface to defend against).
    return join(this.rootDir, objectKey);
  }

  async put(objectKey: string, file: { buffer: Buffer }): Promise<void> {
    const path = this.pathFor(objectKey);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, file.buffer);
  }

  async get(objectKey: string): Promise<Buffer | null> {
    try {
      return await readFile(this.pathFor(objectKey));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw err;
    }
  }

  async delete(objectKey: string): Promise<void> {
    await rm(this.pathFor(objectKey), { force: true });
  }
}

/** Default instance used when callers don't supply their own. */
export const resumeStorage: ResumeStorage = new LocalDiskResumeStorage();
